apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gc-pdf-util.name" . }}-environment
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "gc-pdf-util.labels" . | nindent 4 }}
data:
  AUTH_SERVER_ISSUER: {{ .Values.authServer.issuer | default .Values.authServer.baseUrl | quote }}
  AUTH_SERVER_AUDIENCE: {{ .Values.authServer.audience | default .Values.authServer.baseUrl | quote }}
  AUTH_SERVER_BASE_URL: {{ .Values.authServer.baseUrl | quote }}
  {{- if .Values.additionalEnvConfig }}
  {{- toYaml .Values.additionalEnvConfig | nindent 2 }}
  {{- end }}
