{{ if eq (.Values.useKms | default false) true }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "gc-pdf-util.name" . }}-secret
  namespace: {{.Release.Namespace}}
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: '{{ .Values.secret.store }}' # Must match ClusterSecretStore on the cluster
  target:
    name: {{ include "gc-pdf-util.name" . }}-secret # Name for the secret on the cluster
    creationPolicy: Owner
  data:
{{- range $k, $v := .Values.additionalEnvSecret }}
  - secretKey: {{ $k }}
    remoteRef:
  {{- toYaml $v | nindent 6 }}
{{- end }}
{{- end -}}
