{{ if eq (.Values.useKms | default false) false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gc-pdf-util.name" . }}-secret
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "gc-pdf-util.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.additionalEnvSecret }}
  {{- toYaml .Values.additionalEnvSecret | nindent 2 }}
  {{- end }}
{{- end -}}
