import os

AUTH_SERVER_BASE_URL=os.environ.get("AUTH_SERVER_BASE_URL")

AUTH_SERVER_ENDPOINTS={
    "JWKS_JSON": '/api/oauth2/jwks.json',
}

AUTH_SERVER_ISSUER = os.environ.get("AUTH_SERVER_ISSUER")

AUTH_SERVER_AUDIENCE = os.environ.get("AUTH_SERVER_AUDIENCE", AUTH_SERVER_ISSUER)

CORRUPTED_TEXT_THRESHOLD = os.environ.get("CORRUPTED_TEXT_THRESHOLD", 0.3)
PDF_TO_IMAGE_CONVERSION_DPI = os.environ.get("PDF_TO_IMAGE_CONVERSION_DPI", 300)

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")
MINDS_DB_MODEL_NAME = os.environ.get("MINDS_DB_MODEL_NAME", "bank_statement_agent_prompted_4_4_25_11_23")
MINDS_DB_API_ENDPOINT = os.environ.get("MINDS_DB_API_ENDPOINT", "http://20.174.12.117:47334")