import os

AUTH_SERVER_BASE_URL=os.environ.get("AUTH_SERVER_BASE_URL")

AUTH_SERVER_ENDPOINTS={
    "JWKS_JSON": '/api/oauth2/jwks.json',
}

AUTH_SERVER_ISSUER = os.environ.get("AUTH_SERVER_ISSUER")

AUTH_SERVER_AUDIENCE = os.environ.get("AUTH_SERVER_AUDIENCE", AUTH_SERVER_ISSUER)

CORRUPTED_TEXT_THRESHOLD = os.environ.get("CORRUPTED_TEXT_THRESHOLD", 0.3)
PDF_TO_IMAGE_CONVERSION_DPI = os.environ.get("PDF_TO_IMAGE_CONVERSION_DPI", 300)

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")
# MINDS_DB_MODEL_NAME = os.environ.get("MINDS_DB_MODEL_NAME", "bank_statement_agent_prompted_4_4_25_11_23")
# MINDS_DB_API_ENDPOINT = os.environ.get("MINDS_DB_API_ENDPOINT", "http://20.174.12.117:47334")

# Set API keys from environment variables
GC_AI_API_KEY = os.getenv("GC_AI_API_KEY")
GC_AI_PARSERS_BASE_URL = os.getenv("GC_AI_PARSERS_BASE_URL")
DEFAULT_PDF_CHUNK_SIZE = int(os.getenv("DEFAULT_PDF_CHUNK_SIZE", 5))

DEFAULT_EMBEDDINGS_MODEL = os.getenv("DEFAULT_EMBEDDINGS_MODEL", "azure:text-embedding-ada-002")
DEFAULT_LLM_CHOICE = os.getenv("DEFAULT_LLM_CHOICE", "azure:gpt-4o")

AZURE_OPENAI_MODEL_NAME=os.getenv("AZURE_OPENAI_MODEL_NAME", "gpt-4o")
AZURE_OPENAI_API_KEY=os.getenv("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_ENDPOINT=os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_DEPLOYMENT=os.getenv("AZURE_OPENAI_DEPLOYMENT")

QDRANT_API_KEY = os.getenv("QDRANT_API_KEY")
QDRANT_URL = os.getenv("QDRANT_URL")

QDRANT_COLEARN_COLLECTION_NAME = os.getenv("QDRANT_COLEARN_COLLECTION_NAME", "colearn-test-qdrant-2")
# COLEARN_LLM_CHOICE = os.getenv("COLEARN_LLM_CHOICE", "claude:anthropic.claude-3-5-sonnet-20240620-v1:0")
COLEARN_LLM_CHOICE = os.getenv("COLEARN_LLM_CHOICE", "claude:anthropic.claude-3-5-sonnet-20240620-v1:0")
LOAD_COLEARN = os.getenv("LOAD_COLEARN", "True") == "True"

AWS_ACCESS_KEY_ID=os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY=os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_DEFAULT_REGION=os.getenv("AWS_DEFAULT_REGION")

TAVILY_API_KEY=os.getenv("TAVILY_API_KEY")
FIRECRAWL_API_KEY=os.getenv("FIRECRAWL_API_KEY")
FIRECRAWL_URL=os.getenv("FIRECRAWL_URL")
APIFY_API_TOKEN=os.getenv("APIFY_API_TOKEN")

QDRANT_NGENIUS_COLLECTION_NAME = os.getenv("QDRANT_NGENIUS_COLLECTION_NAME", "ngenius-test-qdrant-2")
LOAD_NGENIUS = os.getenv("LOAD_NGENIUS", "True") == "True"
NGENIUS_LLM_CHOICE = os.getenv("NGENIUS_LLM_CHOICE", "openai:o4-mini")

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")