import os

AUTH_SERVER_BASE_URL=os.environ.get("AUTH_SERVER_BASE_URL")

AUTH_SERVER_ENDPOINTS={
    "JWKS_JSON": '/api/oauth2/jwks.json',
}

AUTH_SERVER_ISSUER = os.environ.get("AUTH_SERVER_ISSUER")

AUTH_SERVER_AUDIENCE = os.environ.get("AUTH_SERVER_AUDIENCE", AUTH_SERVER_ISSUER)