{{- if .Values.volumes.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gc-pdf-util.name" . }}-data-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{ .Values.volumes.storageClassName }}
  volumeMode: Filesystem
{{- end }}
