apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gc-pdf-util.name" . }}
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "gc-pdf-util.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gc-pdf-util.coreSelectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/config/secret.yaml") . | sha256sum }}
      labels:
        {{- include "gc-pdf-util.coreSelectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- include "gc-pdf-util.pull-secrets" . | nindent 8 }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ include "gc-pdf-util.version" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              protocol: TCP
              containerPort: 9433
          livenessProbe:
            initialDelaySeconds: 120
            periodSeconds: 30
            httpGet:
              path: /api/health/live
              port: http
          readinessProbe:
            failureThreshold: 30
            initialDelaySeconds: 15
            periodSeconds: 30
            httpGet:
              path: /api/health/ready
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- include "gc-pdf-util.default-env-config" . | nindent 12 }}
{{- if .Values.volumes.enabled }}
          volumeMounts:
            - name: app-data
              mountPath: /app/data
            - name: cache
              mountPath: /home/gcsns/.cache
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: {{ include "gc-pdf-util.name" . }}-data-claim
        - name: cache
          persistentVolumeClaim:
            claimName: {{ include "gc-pdf-util.name" . }}-cache-claim
{{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}